function createfigure(X1, Y1, Z1, S1, C1, X2, Z2, S2, Z3, X3, Y2, Y3)
%CREATEFIGURE(X1, Y1, Z1, S1, C1, X2, Z2, S2, Z3, X3, Y2, Y3)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  X2:  scatter3 x
%  Z2:  scatter3 z
%  S2:  scatter3 s
%  Z3:  scatter3 z
%  X3:  vector of x data
%  Y2:  vector of y data
%  Y3:  scatter3 y

%  Auto-generated by MATLAB on 18-Oct-2018 14:05:25

% Create figure
figure('InvertHardcopy','off','PaperUnits','centimeters','Color',[1 1 1],...
    'OuterPosition',[1 1 770 579]);
colormap(jet(100));

% Create subplot
subplot1 = subplot(2,2,1);
hold(subplot1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'LineWidth',2);

% Create scatter3
scatter3(X2,X2,Z2,S2,'MarkerEdgeColor',[0 0 0],'Marker','x','LineWidth',2);

% Create xlabel
xlabel('x / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create zlabel
zlabel('z / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create ylabel
ylabel('y / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0 600]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0 600]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(subplot1,[0 600]);
view(subplot1,[-45 30]);
grid(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'CLim',[0 200],'DataAspectRatio',[1 1 1],'FontName','arial',...
    'FontSize',16,'FontWeight','bold','LineWidth',2,'XTick',...
    [0 200 400 600 800 1000],'XTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'YTick',...
    [0 200 400 600 800 1000],'YTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'ZTick',...
    [0 200 400 600 800 1000],'ZTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000']);
% Create axes
axes1 = axes('Position',[0.575 0.65 0.3 0.3]);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'LineWidth',2);

% Create scatter3
scatter3(X2,X2,Z3,S2,'MarkerEdgeColor',[0 0 0],'Marker','x','LineWidth',2);

% Create plot
plot(X3,Y2,'LineWidth',2,'LineStyle','--','Color',[0.5 0.5 0.5]);

% Create xlabel
xlabel('x / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create zlabel
zlabel('z / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create ylabel
ylabel('y / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 600]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 600]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 600]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'CLim',[0 200],'DataAspectRatio',[1 1 1],'FontName','arial',...
    'FontSize',16,'FontWeight','bold','LineWidth',2,'XTick',...
    [0 200 400 600 800 1000],'XTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'YTick',...
    [0 200 400 600 800 1000],'YTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'ZTick',...
    [0 200 400 600 800 1000],'ZTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000']);
% Create axes
axes2 = axes('Position',[0.15 0.15 0.3 0.3]);
hold(axes2,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'LineWidth',2);

% Create scatter3
scatter3(X2,Y3,Z2,S2,'MarkerEdgeColor',[0 0 0],'Marker','x','LineWidth',2);

% Create xlabel
xlabel('x / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create zlabel
zlabel('z / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create ylabel
ylabel('y / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0 600]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 600]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[0 600]);
view(axes2,[0 0]);
box(axes2,'on');
% Set the remaining axes properties
set(axes2,'CLim',[0 200],'DataAspectRatio',[1 1 1],'FontName','arial',...
    'FontSize',16,'FontWeight','bold','LineWidth',2,'XTick',...
    [0 200 400 600 800 1000],'XTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'YTick',...
    [0 200 400 600 800 1000],'YTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'ZTick',...
    [0 200 400 600 800 1000],'ZTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000']);
% Create axes
axes3 = axes('Position',[0.575 0.15 0.3 0.3]);
hold(axes3,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'MarkerFaceColor','flat','MarkerEdgeColor','none',...
    'LineWidth',2);

% Create scatter3
scatter3(Z3,X2,Z2,S2,'MarkerEdgeColor',[0 0 0],'Marker','x','LineWidth',2);

% Create xlabel
xlabel('x / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create zlabel
zlabel('z / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Create ylabel
ylabel('y / nm','FontWeight','bold','FontSize',16,'FontName','arial');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0 600]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[0 600]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[0 600]);
view(axes3,[90 0]);
box(axes3,'on');
% Set the remaining axes properties
set(axes3,'CLim',[0 200],'DataAspectRatio',[1 1 1],'FontName','arial',...
    'FontSize',16,'FontWeight','bold','LineWidth',2,'XTick',...
    [0 200 400 600 800 1000],'XTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'YTick',...
    [0 200 400 600 800 1000],'YTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000'],'ZTick',...
    [0 200 400 600 800 1000],'ZTickLabel',...
    ['0   ';'200 ';'400 ';'600 ';'800 ';'1000']);
% Create colorbar
colorbar('peer',axes3,'Position',[0.91 0.1 0.02 0.8],'LineWidth',1,...
    'FontWeight','bold',...
    'FontSize',16,...
    'FontName','arial');

